str1=str("gaurav is doing python with the help of code with harry")
str2=str("hello boys \n how are you")
print(str2)
print(len(str1))
print(str1.isalnum())
print(str1.isalpha())
print(str1.isnumeric())
print(str1.endswith("rry"))
print(str1.capitalize())
print(str1.count("a"))
print(str1.lower())
print(str1.upper())
print(str1.title())
print(str1.find("doing"))
print(str1.replace("gaurav","he"))